name       : haskell-sha
version    : 1.6.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/SHA-1.6.4.2/SHA-1.6.4.2.tar.gz : c470176f63cbe49fd0502a1b32ef22bc01b1af42385583b8be94547750958a8c
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library implements the SHA suite of message digest functions
description: |
    This library implements the SHA suite of message digest functions, according to NIST FIPS 180-2 (with the SHA-224 addendum), as well as the SHA-based HMAC routines. The functions have been tested against most of the NIST and RFC test vectors for the various functions. While some attention has been paid to performance, these do not presently reach the speed of well-tuned libraries, like OpenSSL.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
